# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 24) do

  create_table "accounts", :force => true do |t|
    t.column "number",          :string
    t.column "created_on",      :datetime
    t.column "company_id",      :integer
    t.column "organization_id", :integer
  end

  add_index "accounts", ["company_id"], :name => "accounts_company_id_index"
  add_index "accounts", ["organization_id"], :name => "accounts_vendor_id_index"
  add_index "accounts", ["company_id", "organization_id"], :name => "accounts_company_id_vendor_id"

  create_table "companies", :force => true do |t|
    t.column "name",                 :string
    t.column "street",               :string
    t.column "city",                 :string
    t.column "state",                :string
    t.column "zipcode",              :string
    t.column "phone_number",         :string
    t.column "web_site",             :string
    t.column "credit_rate",          :float
    t.column "best_commission_rate", :float
    t.column "soft_commission_rate", :float
    t.column "created_on",           :datetime
  end

  create_table "invoices", :force => true do |t|
    t.column "number",       :string
    t.column "amount",       :decimal,  :precision => 63, :scale => 4, :default => 0.0
    t.column "start_date",   :date
    t.column "end_date",     :date
    t.column "check_number", :integer
    t.column "paid_on",      :date
    t.column "notes",        :text
    t.column "created_on",   :datetime
    t.column "payment_id",   :integer
  end

  add_index "invoices", ["payment_id"], :name => "invoices_payment_id_index"
  add_index "invoices", ["paid_on"], :name => "invoices_paid_on_index"

  create_table "organizations", :force => true do |t|
    t.column "name",              :string
    t.column "street",            :string
    t.column "city",              :string
    t.column "state",             :string
    t.column "zipcode",           :string
    t.column "contact",           :string
    t.column "email",             :string
    t.column "phone_number",      :string
    t.column "terms",             :text
    t.column "notes",             :text
    t.column "created_on",        :datetime
    t.column "organization_type", :string
  end

  create_table "payments", :force => true do |t|
    t.column "amount",       :decimal,  :precision => 63, :scale => 4, :default => 0.0
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
    t.column "request",      :text
    t.column "response",     :text
    t.column "user_id",      :integer
    t.column "account_id",   :integer
    t.column "processed_on", :date
    t.column "status",       :string
  end

  add_index "payments", ["user_id"], :name => "payments_user_id_index"
  add_index "payments", ["account_id"], :name => "payments_account_id_index"

  create_table "pictures", :force => true do |t|
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "created_on",   :datetime
    t.column "subject_id",   :integer
    t.column "subject_type", :string
    t.column "size",         :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "trades", :force => true do |t|
    t.column "direction",       :string
    t.column "quantity",        :integer
    t.column "symbol",          :string
    t.column "average_price",   :decimal, :precision => 63, :scale => 4, :default => 0.0
    t.column "made_on",         :date
    t.column "execution_type",  :string
    t.column "company_id",      :integer
    t.column "credit_accrued",  :decimal, :precision => 63, :scale => 4, :default => 0.0
    t.column "commission_paid", :decimal, :precision => 63, :scale => 4, :default => 0.0
  end

  add_index "trades", ["company_id"], :name => "trades_company_id_index"
  add_index "trades", ["made_on"], :name => "trades_made_on_index"
  add_index "trades", ["execution_type"], :name => "trades_execution_type_index"

  create_table "users", :force => true do |t|
    t.column "first_name",   :string
    t.column "last_name",    :string
    t.column "email",        :string
    t.column "password",     :string
    t.column "phone_number", :string
    t.column "admin",        :boolean
    t.column "created_on",   :datetime
    t.column "company_id",   :integer
    t.column "token",        :string
  end

  add_index "users", ["company_id"], :name => "users_company_id_index"
  add_index "users", ["email", "password"], :name => "users_email_index"

end
